#ifndef STREAMINGSERVICELAYER_GLOBAL_H
#define STREAMINGSERVICELAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STREAMINGSERVICELAYER_LIBRARY)
#  define STREAMINGSERVICELAYERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STREAMINGSERVICELAYERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STREAMINGSERVICELAYER_GLOBAL_H
